<h1><?= $this->escape($this->title) ?></h1>
<?php
$stats = $this->matches->stats;
?>
<p><?= $this->escape(sprintf(
    'It took %dms to query the database and %dms to walk through the RRD'
    . ' files to find %d matches in %d data sources at %s',
    $stats->duration_ms_database,
    $stats->duration_ms_rrd,
    $stats->cnt_matches,
    $stats->cnt_checked_datasources,
    $this->last_run
)) ?></p>

<div class="images" data-base-target="_next">
<?php

foreach ($this->matches->matches as $result) {
$titleComponents = array('host', 'service', 'sub_service', 'graph_name');

$lastHost = false;
$lastService = false;

foreach ($result->graphs as $graph) {
    $host = $graph->host;
    $service = $graph->sub_service
        ? $graph->sub_service
        : $graph->service;

    $c = array();
    $urlParams = array();
    foreach ($titleComponents as $component) {
        if ($graph->$component !== null) {
            $c[] = $graph->$component;
            $urlParams[$component] = $graph->$component;
        }
    }
    $urlParams['start'] = $result->start;
    $urlParams['end']   = $result->end;

    if ($lastHost !== $host) {
        echo '<h3>' . $this->escape($host) . "</h3>\n";
    }

    if ($lastService !== $service) {
        echo '<h6 style="border: none">' . $this->escape($service ?: 'Host check') . ":</h6>\n";
    }

    $lastService = $service;
    $lastHost = $host;

    echo '<a href="' . $this->url('rrdstore/render/large', $urlParams) . '">';
    echo $this->img(
        'rrdstore/render/graph',
        array(
            'id'     => $graph->graph_id,
            'width'  => $this->width,
            'height' => $this->height,
            'start'  => $result->start,
            'end'    => $result->end
        ),
        array(
            'title' => implode($c, ' - '),
        )
    ) . "</a>\n";
}
}
?>
</div>
